# Site settings
title: Grayscale
email: jiali.wong@outlook.com
url: https://Hummmm.github.io
description: "My name is Jiali Wang. I am currently both an engineer and a team leader focusing on AR industry. I graduated from Hongkong University, majoring in Computer Science and Mathematics. As for my current interest, I have accepted a PHD offer from Imperial College London. The project is about visual surgeon, developing novel tools using Augmented Reality (AR) and Virual Reality (VR) technologies, exploring the optimal use within improvement of surgical care. However, I have defered the offer next year.
"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: Douban
    url:https://www.douban.com/people/WillGray/
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
